# Generated by Django 2.1.1 on 2018-10-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='DEFAULT VALUE', max_length=200)),
                ('password', models.CharField(default='DEFAULT VALUE', max_length=200)),
                ('typeOfUser', models.CharField(default='DEFAULT VALUE', max_length=100)),
                ('phone_number', models.BigIntegerField(default='2197288966')),
                ('authy_id', models.BigIntegerField(blank=True, null=True)),
                ('email', models.EmailField(default='theemail@yahoo.com', max_length=254)),
                ('securityQ', models.CharField(default='What is your username?1', max_length=5000)),
                ('securityAns', models.CharField(default='DEFAULT VALUE1', max_length=5000)),
            ],
        ),
    ]
