# Generated by Django 2.1.1 on 2018-10-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_account_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='securityAns2',
            field=models.CharField(default='DEFAULT VALUE1', max_length=5000),
        ),
        migrations.AddField(
            model_name='account',
            name='securityQ2',
            field=models.CharField(default='What is your username?1', max_length=5000),
        ),
    ]
