# Generated by Django 2.1.1 on 2018-11-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181026_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='lastLogin',
            field=models.CharField(default='2000-01-01 01:01:01', max_length=500),
        ),
    ]
