# Generated by Django 2.1.1 on 2018-10-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_profile',
            name='DOB',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='patient_profile',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
