# Generated by Django 2.1.1 on 2018-10-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='securityAns',
            field=models.CharField(default='DEFAULT VALUE1', max_length=5000),
        ),
        migrations.AddField(
            model_name='account',
            name='securityQ',
            field=models.CharField(default='What is your username?1', max_length=5000),
        ),
    ]
