# Generated by Django 2.1.1 on 2018-10-05 21:44

from django.db import migrations, models
import users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('objects', users.managers.AccountUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='authy_id',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(default='joemomma@yahoo.com', max_length=254),
        ),
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.IntegerField(default='12345678901'),
        ),
    ]
