# Generated by Django 2.1.1 on 2018-12-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance_recommendation',
            fields=[
                ('patient_username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('insurance_plan', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
