# Generated by Django 2.1.1 on 2018-12-03 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance_recommendation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurance_recommendation',
            old_name='patient_username',
            new_name='username',
        ),
    ]
