# Generated by Django 2.1.1 on 2018-12-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance_recommendation', '0003_insurance_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance_recommendation',
            name='insurance_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
