# Generated by Django 2.1.1 on 2018-12-05 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurance_recommendation', '0005_auto_20181205_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance_recommendation',
            name='current_plan',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
