# Generated by Django 2.1.1 on 2018-12-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_profile',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient_profile',
            name='plan',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
