# Generated by Django 2.1.1 on 2018-10-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient_profile', '0002_auto_20181006_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_profile',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
