# Generated by Django 2.1.1 on 2018-12-04 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient_profile', '0002_auto_20181203_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_profile',
            name='company',
            field=models.CharField(default='Medicare', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient_profile',
            name='plan',
            field=models.CharField(default='standard', max_length=100),
        ),
    ]
