# Generated by Django 2.1.1 on 2018-12-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient_profile', '0004_patient_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_profile',
            name='salary',
            field=models.BigIntegerField(null=True),
        ),
    ]
