# Generated by Django 2.1.1 on 2018-10-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_profile',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('First_name', models.CharField(max_length=100, null=True)),
                ('Last_Name', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('DOB', models.DateField(null=True)),
                ('specialization', models.CharField(max_length=100, null=True)),
                ('Hospital', models.CharField(max_length=100, null=True)),
                ('rating', models.IntegerField(null=True)),
            ],
        ),
    ]
