# Generated by Django 2.1.1 on 2018-10-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_profile',
            name='hourly_charge',
            field=models.IntegerField(null=True),
        ),
    ]
