# Generated by Django 2.1.1 on 2018-10-15 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor_profile', '0002_doctor_profile_hourly_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('appointment', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('reviews', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='doctor_profile',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
