# Generated by Django 2.1.1 on 2018-10-20 21:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor_profile', '0006_remove_doctor_appointments_workingdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_appointments',
            name='workingdays',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None),
        ),
    ]
