# Generated by Django 2.1.1 on 2018-10-20 21:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor_profile', '0008_remove_doctor_appointments_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_appointments',
            name='time',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), null=True, size=None),
        ),
    ]
