# Generated by Django 2.1.1 on 2018-10-20 21:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor_profile', '0015_auto_20181020_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bTime',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='booking',
            name='bdate',
            field=models.DateField(null=True),
        ),
    ]
