# Generated by Django 2.1.1 on 2018-10-23 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor_profile', '0019_merge_20181023_1546'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor_appointment',
        ),
    ]
