# Generated by Django 2.1.1 on 2018-10-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_profile',
            name='insurance_name',
            field=models.CharField(default='Medi Care Gold Plus', max_length=100),
        ),
    ]
