# Generated by Django 2.1.1 on 2018-12-03 19:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('ref_no', models.AutoField(primary_key=True, serialize=False)),
                ('docusername', models.CharField(max_length=100, null=True)),
                ('patientusername', models.CharField(max_length=100, null=True)),
                ('bdate', models.DateField(null=True)),
                ('btime', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), null=True, size=None)),
                ('bill', models.CharField(choices=[('P', 'Paid'), ('UP', 'Unpaid')], default='UP', max_length=10)),
            ],
        ),
    ]
