# Generated by Django 2.1.1 on 2018-11-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor_profile', '0002_doctor_profile_insurance_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_profile',
            name='city_name',
            field=models.CharField(default='Bloomington', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor_profile',
            name='state_name',
            field=models.CharField(default='IN', max_length=100),
        ),
    ]
