# Generated by Django 2.1.1 on 2018-10-31 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor_profile', '0002_doctor_profile_insurance_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_profile',
            name='city_state_name',
            field=models.CharField(default='Bloomington,IN', max_length=100),
        ),
    ]
