# Generated by Django 2.1.1 on 2018-10-31 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor_profile', '0003_doctor_profile_city_state_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor_profile',
            old_name='city_state_name',
            new_name='city_name',
        ),
    ]
