# Generated by Django 2.1.1 on 2018-10-31 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor_profile', '0004_auto_20181030_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_profile',
            name='state_name',
            field=models.CharField(default='IN', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor_profile',
            name='city_name',
            field=models.CharField(default='Bloomington', max_length=100),
        ),
    ]
